- name: Full upgrade
  hosts: all
  tasks:
    - name: Upgrade all packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: full

    - name: Remove unused packages
      ansible.builtin.apt:
        autoremove: yes
