- name: Install Syncthing
  hosts: all
  tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - curl
          - gnupg2
          - ca-certificates
          - lsb-release
          - debian-archive-keyring

    - name: Download gpg key
      ansible.builtin.shell: |
        mkdir -p /etc/apt/keyrings
        curl -L -o /etc/apt/keyrings/syncthing-archive-keyring.gpg https://syncthing.net/release-key.gpg

    - name: Create Syncthing APT sources file
      ansible.builtin.copy:
        content: |
          Types: deb
          URIs: https://apt.syncthing.net/
          Suites: syncthing
          Components: stable-v2
          Signed-By: /etc/apt/keyrings/syncthing-archive-keyring.gpg
        dest: /etc/apt/sources.list.d/syncthing.sources
        owner: root
        group: root
        mode: "0644"
      become: true

    - name: Install Syncthing
      ansible.builtin.apt:
        update_cache: yes
        name: syncthing
        state: latest
